logging:
  structured:
    format:
      console: logstash
    json:
      add:
        service: ${spring.application.name:auth-service}
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
